export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: ProductCategory;
  usage?: string;
  ingredients?: string[];
  benefits?: string[];
  image?: string;
  inStock: boolean;
  rating?: number;
  reviewCount?: number;
  volume?: string;
}

export interface ProductCategory {
  id: string;
  name: string;
  description: string;
  image?: string;
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    id: 'daily-essentials',
    name: 'Daily Essentials',
    description: 'Günlük cilt bakım rutininizin temeli - temizleyiciler, nemlendiriciler ve koruma',
  },
  {
    id: 'age-line',
    name: 'A.G.E. Yaşlanma Karşıtı',
    description: 'Yaşlanma belirtilerine karşı gelişmiş anti-aging tedavi sistemleri',
  },
  {
    id: 'ac-line',
    name: 'A.C. Akne Tedavisi',
    description: 'Akne, fazla sebum ve gözenek problemlerine profesyonel çözümler',
  },
  {
    id: 'mela-line',
    name: 'M.E.L.A. Pigmentasyon',
    description: 'Melasma, leke ve hiperpigmentasyon tedavisi için özel formüller',
  },
  {
    id: 'cr-line',
    name: 'C.R. Kızarıklık Tedavisi',
    description: 'Kronik kızarıklık, hassas cilt ve rozasea için özel bakım',
  },
  {
    id: 'concentrated-serums',
    name: 'Konsantre Serumlar',
    description: 'Yüksek aktif içerikli, hedefli etkili konsantre serum formülleri',
  },
  {
    id: 'homecare-kits',
    name: 'Ev Bakım Kitleri',
    description: 'Komple tedavi sistemleri ve profesyonel ev bakım programları',
  },
];

export const PRODUCTS: Product[] = [
  // Daily Essentials - Günlük Bakım Ürünleri
  {
    id: 'uv-protect-spf50',
    name: 'U.V. protect SPF 50+',
    description: 'Geniş spektrumlu güneş koruması, infrared radyasyona karşı koruma sağlar ve iltihabı azaltır',
    price: 485,
    originalPrice: 540,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Güneşe maruz kalmadan 15 dakika önce cilt üzerine bol miktarda uygulayın. Her 2 saatte bir tekrarlayın.',
    ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Antioxidant Complex', 'Vitamin E', 'Iron Oxides'],
    benefits: ['SPF 50+ koruma', 'UVA/UVB koruması', 'Infrared radyasyon koruması', 'Antioxidant savunma', 'Yağsız formül'],
    image: '/products/placeholder-product.svg',
    rating: 4.8,
    reviewCount: 245,
    inStock: true,
  },
  {
    id: 'exfo-cleanse',
    name: 'E.X.F.O. cleanse',
    description: 'Nazik temizleyici eksfoliant, kaba keratinleşmiş hücreleri gevşeten özel aktifler içerir',
    price: 320,
    volume: '200ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Sabah ve akşam ıslak cilde uygulayın, nazikçe masaj yapın ve iyice durulayın.',
    ingredients: ['AHA Complex', 'BHA Complex', 'Lactic Acid', 'Glycolic Acid'],
    benefits: ['Nazik eksfoliant', 'Ölü deri hücrelerini temizler', 'Cilt dokusunu geliştirir', 'Gözenekleri açar'],
    image: '/products/placeholder-product.svg',
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
  },
  {
    id: 'hydra-serum',
    name: 'HYDRA serum',
    description: 'Aktif bileşenlerin özel karışımı ve nem bağlayıcı maddelerle yoğun nemlendirme',
    price: 395,
    originalPrice: 440,
    volume: '30ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Temizlenen cilde sabah ve akşam, nemlendirici öncesi uygulayın.',
    ingredients: ['Hyaluronic Acid', 'Sodium PCA', 'Glycerin', 'Panthenol', 'Allantoin'],
    benefits: ['Yoğun nemlendirme', 'Cildi dolgunlaştırır', 'Uzun süreli nem', 'Cilt bariyerini güçlendirir'],
    image: '/products/placeholder-product.svg',
    rating: 4.9,
    reviewCount: 412,
    inStock: true,
  },
  {
    id: 'post-recovery-cream',
    name: 'P.O.S.T. recovery cream',
    description: 'Maksimum nemlendirme, anti-inflamatuar ve antioksidan özellikli zengin emülsiyon krem',
    price: 445,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Tedavi sonrası cildi sakinleştirmek için günde 2-3 kez uygulayın.',
    ingredients: ['Shea Butter', 'Ceramides', 'Niacinamide', 'Bisabolol', 'Vitamin E'],
    benefits: ['Maksimum nemlendirme', 'İltihabı azaltır', 'Cildi sakinleştirir', 'Hızlı iyileşme'],
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
  },
  {
    id: 'active-formula-daily',
    name: 'A.C.T.I.V.E. formula',
    description: 'Tüm cilt bozukluklarını normalleştiren ve genel sağlığı koruyan hazırlık tedavisi ürünü',
    price: 365,
    volume: '30ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Temiz cilde akşam uygulanır. Tedaviye başlamadan 2 hafta önce kullanıma başlayın.',
    ingredients: ['Mandelic Acid', 'Lactic Acid', 'Salicylic Acid', 'Niacinamide'],
    benefits: ['Cildi tedaviye hazırlar', 'Toleransı artırır', 'Normalleştirici', 'Çok amaçlı'],
    rating: 4.6,
    reviewCount: 234,
    inStock: true,
  },

  // A.G.E. Line - Yaşlanma Karşıtı Ürünler
  {
    id: 'age-recovery',
    name: 'A.G.E. recovery',
    description: 'Yüzeysel çizgiler dahil yaşlanma belirtilerini azaltan gelişmiş yaş karşıtı cilt yüzeyi yenileme tedavisi',
    price: 595,
    originalPrice: 660,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[1],
    usage: 'Sadece akşam temiz cilde uygulayın. Gündüz SPF kullanımı zorunludur.',
    ingredients: ['Retinol', 'Peptide Complex', 'Vitamin C', 'Hyaluronic Acid', 'Glycolic Acid'],
    benefits: ['İnce çizgileri azaltır', 'Elastikiyeti artırır', 'Cilt tonunu eşitler', 'Pürüzsüz görünüm'],
    rating: 4.9,
    reviewCount: 378,
    inStock: true,
  },
  {
    id: 'vita-a-cream',
    name: 'VITA A cream',
    description: 'Hücre yenilenmesini uyaran, ince çizgiler, kırışıklıklar ve yaş lekelerini azaltan saf retinol içerir',
    price: 525,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[1],
    usage: 'Akşam temiz cilde az miktarda uygulayın. Güneş hassasiyeti yaratabilir.',
    ingredients: ['Pure Retinol', 'Vitamin E', 'Squalane', 'Ceramides'],
    benefits: ['Hücre yenilenmesi', 'Çizgileri azaltır', 'Yaş lekelerini azaltır', 'Saf retinol'],
    rating: 4.7,
    reviewCount: 289,
    inStock: true,
  },
  {
    id: 'age-homecare-kit',
    name: 'A.G.E. homecare kit',
    description: 'Yaşlanma karşıtı ev bakım kiti - komple anti-aging sistemi',
    price: 1250,
    originalPrice: 1450,
    category: PRODUCT_CATEGORIES[1],
    usage: 'Kit içindeki protokolü takip edin. Profesyonel rehberlik önerilir.',
    benefits: ['Komple anti-aging sistem', 'Profesyonel sonuçlar', 'Evde kullanım', 'Kapsamlı bakım'],
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
  },

  // A.C. Line - Akne Tedavisi
  {
    id: 'ac-recovery',
    name: 'A.C. recovery',
    description: 'Akne grade I, II ve III, aşırı sebum, genişlemiş gözenekler ve yüzeysel skarlar için',
    price: 495,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[2],
    usage: 'Temiz cilde sabah ve akşam uygulayın. Başlangıçta kuruluk yaratabilir.',
    ingredients: ['Salicylic Acid', 'Benzoyl Peroxide', 'Niacinamide', 'Zinc PCA', 'Tea Tree Oil'],
    benefits: ['Akne lezyonlarını temizler', 'Yeni akne oluşumunu önler', 'İltihabı azaltır', 'Sebum kontrolü'],
    rating: 4.6,
    reviewCount: 267,
    inStock: true,
  },
  {
    id: 'ac-homecare-kit',
    name: 'A.C. homecare kit',
    description: 'Akne tedavisi için komple ev bakım sistemi',
    price: 1150,
    originalPrice: 1320,
    category: PRODUCT_CATEGORIES[2],
    usage: 'Kit protokolünü takip edin. Tolerans geliştirmek için yavaş başlayın.',
    benefits: ['Komple akne çözümü', 'Profesyonel güçte', 'Temiz cilt sonuçları', 'Sistematik tedavi'],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
  },

  // M.E.L.A. Line - Pigmentasyon Tedavisi
  {
    id: 'mela-recovery',
    name: 'M.E.L.A. recovery',
    description: 'Melasma, kloasma, UV kaynaklı hiperpigmentasyon ve post-inflamatuar hiperpigmentasyon için',
    price: 565,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[3],
    usage: 'Sadece akşam lekeli bölgelere uygulayın. Gündüz SPF kullanımı zorunludur.',
    ingredients: ['Kojic Acid', 'Arbutin', 'Vitamin C', 'Azelaic Acid', 'Licorice Extract'],
    benefits: ['Hiperpigmentasyonu azaltır', 'Cilt tonunu eşitler', 'Koyu lekeleri açar', 'Aydınlatıcı etki'],
    rating: 4.8,
    reviewCount: 203,
    inStock: true,
  },
  {
    id: 'mela-serum',
    name: 'M.E.L.A. serum',
    description: 'Konsantre pigmentasyon tedavi serumu, hedefli leke giderici aktifler',
    price: 475,
    originalPrice: 530,
    volume: '30ml',
    category: PRODUCT_CATEGORIES[3],
    usage: 'Lekeli bölgelere akşam uygulayın. Gündüz SPF kullanın.',
    ingredients: ['Hydroquinone Alternative', 'Kojic Acid', 'Vitamin C', 'Alpha Arbutin'],
    benefits: ['Konsantre aktifler', 'Koyu lekeleri hedefler', 'Eşit ten tonu', 'Hızlı sonuç'],
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
  },
  {
    id: 'mela-powerclays',
    name: 'M.E.L.A. powerclays',
    description: 'Pigmentasyon için özel kil maskesi, derinlemesine temizlik ve aydınlatma',
    price: 395,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[3],
    usage: 'Haftada 1-2 kez, temiz cilde ince tabaka halinde uygulayın, 15-20 dakika bekleyin.',
    ingredients: ['White Clay', 'Charcoal', 'Kojic Acid', 'Vitamin C'],
    benefits: ['Derinlemesine temizlik', 'Pigmentasyonu azaltır', 'Parlaklık verir', 'Gözenekleri temizler'],
    rating: 4.5,
    reviewCount: 134,
    inStock: true,
  },

  // C.R. Line - Kızarıklık Tedavisi
  {
    id: 'cr-recovery',
    name: 'C.R. recovery',
    description: 'Kızarıklık belirtileri gösteren ciltler için formüle edilmiş, hassas ve rozasea eğilimli ciltler için uygun',
    price: 485,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[4],
    usage: 'Etkilenen bölgelere günde iki kez uygulayın. Hassas ciltler için nazik.',
    ingredients: ['Azelaic Acid', 'Niacinamide', 'Centella Asiatica', 'Bisabolol', 'Green Tea Extract'],
    benefits: ['Kızarıklığı azaltır', 'İltihabı yatıştırır', 'Cilt bariyerini güçlendirir', 'Hassas cilt dostu'],
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
  },
  {
    id: 'cr-homecare-kit',
    name: 'C.R. homecare kit',
    description: 'Kızarıklık ve hassasiyet tedavisi sistemi',
    price: 995,
    category: PRODUCT_CATEGORIES[4],
    usage: 'Kit protokolünü takip edin. Hassas ciltler için nazik.',
    benefits: ['Kronik kızarıklığı azaltır', 'Nazik tedavi', 'Yatıştırıcı formül', 'Sistematik yaklaşım'],
    rating: 4.6,
    reviewCount: 78,
    inStock: false,
  },

  // Concentrated Serums - Konsantre Serumlar
  {
    id: 'vita-c-serum',
    name: 'VITA C serum',
    description: 'Aydınlatıcı vitamin C antioksidan serumu, çevre koruması ve parlaklık için',
    price: 425,
    originalPrice: 475,
    volume: '30ml',
    category: PRODUCT_CATEGORIES[5],
    usage: 'Sabah temizlik sonrası uygulayın. Mutlaka SPF ile takip edin.',
    ingredients: ['L-Ascorbic Acid', 'Vitamin E', 'Ferulic Acid', 'Hyaluronic Acid'],
    benefits: ['Vitamin C antioksidanı', 'Cildi aydınlatır', 'Çevresel koruma', 'Parlaklık verir'],
    rating: 4.9,
    reviewCount: 345,
    inStock: true,
  },
  {
    id: 'age-serum',
    name: 'age serum',
    description: 'Premium yaşlanma karşıtı serum, peptid kompleksi ile lüks formülasyon',
    price: 595,
    volume: '36ml',
    category: PRODUCT_CATEGORIES[5],
    usage: 'Sabah ve akşam temizlik sonrası uygulayın. Uygun nemlendiriciler ile takip edin.',
    ingredients: ['Peptide Complex', 'Retinyl Palmitate', 'Hyaluronic Acid', 'Antioxidant Blend'],
    benefits: ['Premium yaşlanma karşıtı', 'Peptid kompleksi', 'Lüks formülasyon', 'Çok etkili'],
    rating: 4.8,
    reviewCount: 123,
    inStock: true,
  },
  {
    id: 'spot-on',
    name: 'spot ON',
    description: 'Noktasal leke tedavisi, hedefli bölgesel uygulama için özel formül',
    price: 285,
    volume: '15ml',
    category: PRODUCT_CATEGORIES[5],
    usage: 'Tek tek lekelere gerektiğinde uygulayın. Hızlı etkili formül.',
    ingredients: ['Hydroquinone Alternative', 'Kojic Acid', 'Salicylic Acid'],
    benefits: ['Hedefli tedavi', 'Hızlı sonuçlar', 'Pratik uygulama', 'Konsantre etki'],
    rating: 4.5,
    reviewCount: 198,
    inStock: true,
  },

  // Homecare Kits - Ev Bakım Kitleri
  {
    id: 'inside-out-kit',
    name: 'inside OUT kit',
    description: 'İçten dışa kapsamlı cilt bakım sistemi',
    price: 850,
    originalPrice: 950,
    category: PRODUCT_CATEGORIES[6],
    usage: 'Kit içindeki tam protokolü takip edin.',
    benefits: ['İçten dışa bakım', 'Kapsamlı sistem', 'Profesyonel sonuçlar', 'Holistik yaklaşım'],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
  },
  {
    id: 'sos-kit',
    name: 'S.O.S. kit',
    description: 'Acil durum cilt bakım kiti, hızlı müdahale için',
    price: 395,
    volume: 'Kit',
    category: PRODUCT_CATEGORIES[6],
    usage: 'Acil cilt problemlerinde hızlı müdahale için kullanın.',
    benefits: ['Acil müdahale', 'Hızlı etki', 'Çok amaçlı', 'Pratik çözüm'],
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
  },
  {
    id: 'point-kit',
    name: 'point kit',
    description: 'Noktasal tedaviler için özel kit',
    price: 425,
    category: PRODUCT_CATEGORIES[6],
    usage: 'Spesifik problemli bölgeler için hedefli uygulama.',
    benefits: ['Noktasal tedavi', 'Hedefli etki', 'Hassas uygulama', 'Profesyonel sonuç'],
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
  },

  // Additional Popular Products
  {
    id: 'daily-defense-spf',
    name: 'daily DEFENSE SPF',
    description: 'Günlük koruma faktörü, çevresel etkenlerden korunma',
    price: 365,
    volume: '50ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Sabah bakım rutininizin son adımı olarak uygulayın.',
    ingredients: ['Zinc Oxide', 'Antioxidants', 'Niacinamide'],
    benefits: ['Günlük koruma', 'Çevresel savunma', 'Hafif doku', 'Her gün kullanım'],
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
  },
  {
    id: 'clarifying-toner',
    name: 'clarifying TONER',
    description: 'Netleştirici toner, gözenek temizliği ve pH dengelemesi',
    price: 245,
    volume: '200ml',
    category: PRODUCT_CATEGORIES[0],
    usage: 'Temizlik sonrası pamuk ile cilde uygulayın.',
    ingredients: ['Salicylic Acid', 'Witch Hazel', 'Niacinamide'],
    benefits: ['Gözenekleri temizler', 'pH dengeyi sağlar', 'Netleştirici', 'Sebum kontrolü'],
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
  },
];